[package]
name = "psc-domain"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
rust_decimal = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
psc-error = { workspace = true }
rust_decimal_macros = { workspace = true }
num-traits = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
