[package]
name = "psc-domain"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
rust_decimal = { workspace = true, features = ["serde-with-str"] }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }

[dev-dependencies]
anyhow = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
