[package]
name = "psc-provider"
version = "0.1.0"
edition = "2024"
authors = ["PSC Team"]
description = "Shared Provider trait and MockProvider for unified provider gateway"
license = "MIT"

[dependencies]
async-trait = "0.1"
thiserror = "1.0"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "time", "sync"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "time", "sync"] }