[package]
name = "psc-idempotency"
version = "0.1.0"
edition = "2021"

[dependencies]
psc-error = { path = "../psc-error" }
redis = { version = "0.25.0", features = ["tokio-comp"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1.77"

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }