[package]
name = "psc-telemetry"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true }
tonic = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
opentelemetry-prometheus = { workspace = true }
axum-otel-metrics = { workspace = true }
prometheus = { workspace = true }
