services:
  postgres:
    image: postgres
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-giss}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-giss-password}
      POSTGRES_DB: ${POSTGRES_DB:-giss}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  adminer:
    image: adminer
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    ports:
      - ${ADMINER_PORT:-18080}:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USERNAME: ${POSTGRES_USER:-giss}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-giss-password}
      ADMINER_DESIGN: ${ADMINER_DESIGN:-dracula}
      ADMINER_PLUGINS: ${ADMINER_PLUGINS:-tables-filter tinymce}

volumes:
  db: {}
