[package]
name = "psc-config"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
camino = "1.1.7"
config = { version = "0.14.0", features = ["yaml", "json", "toml", "ini", "ron"] }
serde = { workspace = true }
psc-error = { workspace = true }

[lints]
workspace = true
