name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Generate protos
        run: scripts/generate_proto.sh

  lint:
    runs-on: ubuntu-latest
    needs: proto
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          curl -sSfL https://sh.rustup.rs -s -- -y
          rustup default stable
      - name: Run linters
        run: |
          cargo clippy --all-targets --all-features -- -D warnings || true

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          cargo test --workspace --all-features

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build artifacts
        run: |
          cargo build --workspace --release