name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install protoc (via apt) and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          # Install protobuf plugins for Go and gateway/OpenAPI using go install
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest

      - name: Run proto generation
        run: |
          make proto-gen

      - name: Run tests
        run: |
          # Add test steps as appropriate for the repository
          echo "No tests configured in CI workflow yet"